'use client';

import React, { useEffect, useState } from 'react';
import { AppShell } from '@/components/AppShell';
import { Header } from '@/components/Header';
import { fetchApi } from '@/lib/api';
import {
  Flame,
  ShieldAlert,
  ShieldCheck,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Play,
  RotateCcw,
  Lock,
  ArrowRight,
  TrendingDown,
  CreditCard,
} from 'lucide-react';

export default function AttackLabPage() {
  const [presets, setPresets] = useState<any[]>([]);
  const [selectedScenarioId, setSelectedScenarioId] = useState<string>('amount-override');
  const [loading, setLoading] = useState(false);
  const [progressStep, setProgressStep] = useState<string | null>(null);
  const [result, setResult] = useState<any | null>(null);

  useEffect(() => {
    fetchApi<any[]>('/api/attack-lab/presets')
      .then((data) => {
        setPresets(data);
      })
      .catch((err) => console.error(err));
  }, []);

  const runSimulation = async () => {
    setLoading(true);
    setResult(null);

    // Progressive verification animation
    const steps = [
      'Checking agent identity...',
      'Validating capabilities...',
      'Verifying mandate bounds...',
      'Comparing intent vs action...',
      'Calculating deterministic risk...',
      'Appending cryptographic audit event...',
      'Finalizing authorization...',
    ];

    for (const s of steps) {
      setProgressStep(s);
      await new Promise((r) => setTimeout(r, 160));
    }

    try {
      const res = await fetchApi<any>('/api/attack-lab/simulate', {
        method: 'POST',
        body: JSON.stringify({ scenarioId: selectedScenarioId }),
      });
      setResult(res);
    } catch (err: any) {
      alert(err.message || 'Simulation error');
    } finally {
      setLoading(false);
      setProgressStep(null);
    }
  };

  const selectedPreset = presets.find((p) => p.id === selectedScenarioId);

  return (
    <AppShell>
      <Header
        title="Attack Lab"
        subtitle="Simulate adversarial agent behavior against the identical deterministic authorization engine used for production payments."
        badge="SECURITY TESTBED"
      />

      <main className="p-8 space-y-8 max-w-7xl">
        {/* Google ADK Shopping Agent Banner */}
        <div className="bg-gradient-to-r from-indigo-900/40 via-purple-900/30 to-slate-900 border border-indigo-500/30 rounded-2xl p-4 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <span className="p-2 rounded-xl bg-indigo-500/20 text-indigo-400 border border-indigo-500/30">
              <Flame className="w-5 h-5 text-indigo-400" />
            </span>
            <div>
              <div className="text-sm font-bold text-white flex items-center gap-2">
                Live AI Shopping Agent (Google ADK)
                <span className="text-[10px] font-mono bg-indigo-500/20 text-indigo-300 px-2 py-0.5 rounded-full border border-indigo-500/30">
                  GEMINI + LEO
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Test real-time autonomous purchase actions generated by ShoppingAgent-01 and governed by LEO.
              </p>
            </div>
          </div>
          <a
            href="/agent"
            className="inline-flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold bg-indigo-600 hover:bg-indigo-500 text-white transition shadow-lg shadow-indigo-600/30 shrink-0"
          >
            <span>Open Shopping Agent</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </a>
        </div>

        {/* Scenario Selection Grid */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="text-sm font-bold text-slate-900">Adversarial Vector Scenarios</h3>
              <p className="text-xs text-slate-500">
                Select an attack pattern to dispatch to the LEO authorization engine
              </p>
            </div>
            <span className="text-xs font-mono text-slate-500">
              7 DETERMINISTIC VECTORS READY
            </span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
            {presets.map((sc) => {
              const isSelected = sc.id === selectedScenarioId;
              const isLegit = sc.id === 'legitimate-purchase';
              return (
                <div
                  key={sc.id}
                  onClick={() => setSelectedScenarioId(sc.id)}
                  className={`p-4 rounded-2xl border cursor-pointer transition-all ${
                    isSelected
                      ? 'bg-blue-50/70 border-blue-500 shadow-xs ring-1 ring-blue-500/30'
                      : 'bg-white border-slate-200 hover:bg-slate-50'
                  }`}
                >
                  <div className="flex items-center justify-between mb-2">
                    <span
                      className={`text-[10px] font-mono font-bold uppercase tracking-wider px-2 py-0.5 rounded ${
                        isLegit
                          ? 'bg-emerald-100 text-emerald-800'
                          : 'bg-rose-100 text-rose-800'
                      }`}
                    >
                      {sc.category}
                    </span>
                    <span className="text-slate-400 text-[10px] font-mono">
                      {sc.payload?.amount ? `₹${(sc.payload.amount / 100).toLocaleString()}` : ''}
                    </span>
                  </div>
                  <h4 className="text-xs font-bold text-slate-900 mb-1.5">{sc.name}</h4>
                  <p className="text-[11px] text-slate-500 leading-relaxed line-clamp-2">
                    {sc.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>

        {/* Execution Control Banner */}
        {selectedPreset && (
          <div className="p-6 rounded-2xl bg-white border border-slate-200 shadow-xs flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <span className="text-xs font-bold text-slate-900">Target Scenario:</span>
                <span className="text-xs font-mono text-blue-600 font-bold">
                  {selectedPreset.name}
                </span>
              </div>
              <p className="text-xs text-slate-500 max-w-2xl">
                {selectedPreset.description}
              </p>
            </div>

            <button
              onClick={runSimulation}
              disabled={loading}
              className="px-6 py-3 rounded-xl bg-slate-950 hover:bg-slate-800 text-white font-semibold text-xs shadow-md flex items-center gap-2 disabled:opacity-50 transition-all shrink-0"
            >
              {loading ? (
                <>
                  <div className="w-3.5 h-3.5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  <span>{progressStep}</span>
                </>
              ) : (
                <>
                  <Play className="w-3.5 h-3.5 fill-current" />
                  <span>Dispatch Vector Simulation</span>
                </>
              )}
            </button>
          </div>
        )}

        {/* ATTACK RESULT UI (Selective Dark Box for Cryptographic/Attack Trace Depth) */}
        {result && (
          <div className="space-y-6 pt-2 animate-in fade-in duration-300">
            {/* Special Intent Drift Visualization if Intent Drift scenario */}
            {selectedScenarioId === 'intent-drift' && (
              <div className="p-6 rounded-2xl bg-rose-950 text-white border border-rose-800/60 space-y-4 shadow-xl">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <AlertTriangle className="w-5 h-5 text-rose-400" />
                    <h3 className="text-sm font-bold text-white uppercase tracking-wider">
                      Intent Drift Deep Comparison
                    </h3>
                  </div>
                  <span className="px-2.5 py-1 rounded bg-rose-900 text-rose-200 border border-rose-700 text-[11px] font-mono font-bold tracking-wider">
                    INTENT DRIFT DETECTED
                  </span>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs font-mono">
                  <div className="p-4 rounded-xl bg-slate-950 border border-rose-900/60 space-y-1">
                    <span className="text-slate-400 text-[10px] uppercase">Product Divergence</span>
                    <div className="text-slate-400 line-through">Keyboard</div>
                    <div className="text-rose-400 font-bold text-sm flex items-center gap-1.5">
                      <ArrowRight className="w-3.5 h-3.5" /> Gaming Laptop
                    </div>
                  </div>

                  <div className="p-4 rounded-xl bg-slate-950 border border-rose-900/60 space-y-1">
                    <span className="text-slate-400 text-[10px] uppercase">Financial Divergence</span>
                    <div className="text-slate-400 line-through">₹5,000 Bound</div>
                    <div className="text-rose-400 font-bold text-sm flex items-center gap-1.5">
                      <ArrowRight className="w-3.5 h-3.5" /> ₹72,000 (14.4x Breach)
                    </div>
                  </div>

                  <div className="p-4 rounded-xl bg-slate-950 border border-rose-900/60 space-y-1">
                    <span className="text-slate-400 text-[10px] uppercase">Vendor Authorization</span>
                    <div className="text-slate-400 line-through">Mandated Amazon</div>
                    <div className="text-rose-400 font-bold text-sm flex items-center gap-1.5">
                      <ArrowRight className="w-3.5 h-3.5" /> Mandate Override Attempt
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Standard 4-Section Attack Evaluation Report */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* 1. Attack Input & Analysis */}
              <div className="p-6 rounded-2xl bg-slate-950 text-slate-100 border border-slate-800 space-y-5 text-xs shadow-md">
                <div>
                  <span className="text-[10px] font-mono uppercase tracking-wider text-blue-400">
                    Vector Payload
                  </span>
                  <h4 className="text-sm font-bold text-white mt-0.5">1. Attack Input</h4>
                </div>

                <div className="space-y-2 font-mono text-[11px] p-4 rounded-xl bg-slate-900 border border-slate-800">
                  <div className="flex justify-between">
                    <span className="text-slate-400">Instructed Intent:</span>
                    <span className="text-slate-200 text-right max-w-xs truncate">
                      {result.attackInput.userIntent}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Attempted Merchant:</span>
                    <span className="text-white font-bold">
                      {result.attackInput.agentAction.merchant}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Attempted Item:</span>
                    <span className="text-white">
                      {result.attackInput.agentAction.product}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Requested Amount:</span>
                    <span className="text-rose-400 font-bold">
                      ₹{(result.attackInput.agentAction.amount / 100).toLocaleString()}
                    </span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Required Capability:</span>
                    <span className="text-blue-400 font-mono">
                      {result.attackInput.attemptedCapability}
                    </span>
                  </div>
                </div>

                <div>
                  <h4 className="text-sm font-bold text-white mb-2">2. LEO Analysis</h4>
                  <div className="space-y-1.5 font-mono text-[11px]">
                    {result.evaluation.checks.map((chk: any, idx: number) => (
                      <div
                        key={idx}
                        className={`p-2.5 rounded-lg border flex items-center justify-between ${
                          chk.status === 'PASSED'
                            ? 'bg-emerald-950/30 border-emerald-900/50 text-emerald-300'
                            : 'bg-rose-950/30 border-rose-900/50 text-rose-300'
                        }`}
                      >
                        <div className="flex items-center gap-2">
                          {chk.status === 'PASSED' ? (
                            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                          ) : (
                            <XCircle className="w-3.5 h-3.5 text-rose-400" />
                          )}
                          <span>{chk.name}</span>
                        </div>
                        <span className="text-[10px] text-slate-400 truncate max-w-xs">
                          {chk.details}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* 2. Policy Violations & Final Decision */}
              <div className="p-6 rounded-2xl bg-slate-950 text-slate-100 border border-slate-800 flex flex-col justify-between space-y-5 text-xs shadow-md">
                <div>
                  <span className="text-[10px] font-mono uppercase tracking-wider text-rose-400">
                    Engine Verdict
                  </span>
                  <h4 className="text-sm font-bold text-white mt-0.5">
                    3. Policy Violations & Reason Codes
                  </h4>

                  <div className="space-y-2 mt-3">
                    {result.evaluation.decisionReasons.map((code: string, idx: number) => (
                      <div
                        key={idx}
                        className={`px-3 py-2 rounded-lg font-mono text-xs font-semibold tracking-wide border flex items-center justify-between ${
                          result.evaluation.decision === 'APPROVED'
                            ? 'bg-emerald-950/40 border-emerald-800 text-emerald-300'
                            : 'bg-rose-950/40 border-rose-800 text-rose-300'
                        }`}
                      >
                        <span>{code}</span>
                        <span className="text-[10px] opacity-75">DETERMINISTIC_REASON</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Final Decision & Trust Impact */}
                <div className="p-5 rounded-xl bg-slate-900 border border-slate-800 space-y-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <span className="text-[10px] font-mono uppercase text-slate-400">
                        Final Authorization Outcome
                      </span>
                      <div
                        className={`text-2xl font-bold font-mono tracking-tight ${
                          result.evaluation.decision === 'APPROVED'
                            ? 'text-emerald-400'
                            : 'text-rose-400'
                        }`}
                      >
                        {result.evaluation.decision}
                      </div>
                    </div>
                    <div className="text-right">
                      <span className="text-[10px] font-mono uppercase text-slate-400">
                        Risk Score
                      </span>
                      <div className="text-xl font-bold font-mono-tabular text-white">
                        {result.evaluation.riskScore}
                        <span className="text-xs font-normal text-slate-400">/100</span>
                      </div>
                    </div>
                  </div>

                  {/* Trust Impact Box */}
                  {result.evaluation.trustImpact && (
                    <div className="p-3 rounded-lg bg-slate-950 border border-slate-800 flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <TrendingDown className="w-4 h-4 text-rose-400" />
                        <div>
                          <span className="text-[11px] font-semibold text-white block">
                            Agent Trust Score Penalty
                          </span>
                          <span className="text-[10px] text-slate-400 font-mono">
                            Reason: {result.evaluation.trustImpact.reason}
                          </span>
                        </div>
                      </div>
                      <div className="font-mono text-xs font-bold text-rose-400">
                        {result.evaluation.trustImpact.previousScore} → {result.evaluation.trustImpact.newScore}
                      </div>
                    </div>
                  )}

                  {/* Razorpay Rail Status */}
                  <div className="flex items-center justify-between text-[11px] font-mono text-slate-400 pt-2 border-t border-slate-800">
                    <div className="flex items-center gap-1.5">
                      <CreditCard className="w-3.5 h-3.5 text-blue-400" />
                      <span>Razorpay Settlement Rail:</span>
                    </div>
                    <span className="font-semibold text-white">
                      {result.evaluation.razorpayOrder
                        ? `TEST ORDER ${result.evaluation.razorpayOrder.orderId}`
                        : 'ZERO CALL (BLOCKED)'}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>
    </AppShell>
  );
}
